# Generated by Django 5.0.7 on 2024-08-01 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logpipe', '0006_alter_kafkaoffset_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kafkaoffset',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='kinesisoffset',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
